2:
  id:
    value: '2'
  uuid:
    value: 77bf4997-c472-4869-9a2d-41e8d6b460e9
  langcode:
    value: fr
  bundle:
    value: menu_link_content
  title:
    value: Classement
  description:
    value: ''
  menu_name:
    value: main
  link:
    uri: 'internal:/classement/tests-d8/date-de-passage'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-46'
  expanded:
    value: '1'
  enabled:
    value: '1'
  parent:
    value: ''
  changed:
    value: '1530538941'
  default_langcode:
    value: '1'
